#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Labb2.Resource", IsApplication=true)]

namespace Labb2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Labb2.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Labb2.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int account_array = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int cost_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int income_array = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int tax_array = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int account_spinner = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int calculated_total_without_tax_text = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int cost_radio_button = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int date_edit = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int date_picker_button = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int date_text = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int delete_entry_button = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int entries_list_view = 2131165207;
			
			// aapt resource value: 0x7f070026
			public const int entry_amount_text = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int entry_date_text = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int entry_desc_text = 2131165221;
			
			// aapt resource value: 0x7f070007
			public const int entry_description_edit = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int entry_description_text = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int income_radio_button = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int new_button = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int new_entry_text = 2131165184;
			
			// aapt resource value: 0x7f070016
			public const int report_button = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int save_entry_button = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int show_button = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int tax_spinner = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int tax_text = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int to_from_account_text = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int total_with_tax_edit = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int total_with_tax_text = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int total_without_tax_text = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int type_spinner = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int type_text = 2131165192;
			
			// aapt resource value: 0x7f070018
			public const int view_date_label_text = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int view_date_text = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int view_entry_description_label_text = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int view_entry_description_text = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int view_tax_label_text = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int view_tax_text = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int view_to_from_account_label_text = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int view_to_from_account_text = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int view_total_with_tax_label_text = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int view_total_with_tax_text = 2131165217;
			
			// aapt resource value: 0x7f07001c
			public const int view_type_label_text = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int view_type_text = 2131165213;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_create_new_entry = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_create_reports = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_show_all_entries = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_view_entry = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int entry_list_item = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int cost_radio_button_label = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int create_new = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int create_reports = 2130968580;
			
			// aapt resource value: 0x7f040019
			public const int currency = 2130968601;
			
			// aapt resource value: 0x7f04000a
			public const int date_format = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int date_label = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int date_picker = 2130968584;
			
			// aapt resource value: 0x7f040018
			public const int delete_entry_label = 2130968600;
			
			// aapt resource value: 0x7f04000c
			public const int entry_created = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int entry_description_label = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int entry_not_found = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int entry_updated = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int income_radio_button_label = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int new_entry_label = 2130968581;
			
			// aapt resource value: 0x7f040017
			public const int save_entry_label = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int select_account = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int select_tax = 2130968597;
			
			// aapt resource value: 0x7f040010
			public const int select_type = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int show_all = 2130968579;
			
			// aapt resource value: 0x7f040014
			public const int tax_label = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int to_from_account_label = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int total_with_tax_label = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int total_without_tax_label = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int type_label = 2130968591;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
